# Generated by Django 4.2.2 on 2023-07-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=11, upload_to='products/'),
            preserve_default=False,
        ),
    ]
